### ISSUE TITLE
Uses poppler's private headers

### ISSUE THREAD

**Issue by perezmeyer** [Boomaga/boomaga#33]
Hi! I'm maintaining Boomaga for Debian .I have been asked by one of the poppler-qt  maintainers @pinotree why Boomaga uses it's private API. He even told me that if new public API is needed in poppler-qt (which you don't seems to be using) it would be good to know it.

Maybe we can work out how to solve this :)

Thanks in advance!

**Comment by SokoloffA** [comment]
I use poppler on two manner. 

**For rendering**. I use poppler-cpp instead of the poppler-qt because some time ago poppler was unstable for Qt5. And I wanted to have a version of the boomaga for Qt5 . 
[render function](https://github.com/Boomaga/boomaga/blob/master/gui/kernel/render.cpp#L141)

**For low level PDF handling**. In my program I merge several PDF files into one, changing the number of objects in PDF. Create new pages that contain links to other pages, translate, rotate and scale page. 
I'm not thrilled about having to use the low level API, I even had to write a wrappers for compatibility with different poppler versions.  But when API of poppler-qt and poppler-cpp they had no functions to work with PDF at such low level.
[merging PDF files](https://github.com/Boomaga/boomaga/blob/master/gui/pdfmerger/pdfmerger.cpp)
[creating custom pages](https://github.com/Boomaga/boomaga/blob/master/gui/kernel/tmppdffile.cpp)
