### ISSUE TITLE
[SOLVED] boomaga GUI opens from command line, but not when printed via apps like firefox!

### ISSUE THREAD

**Issue by zenny** [Boomaga/boomaga#98]
Hi,

I am having a strange issue. Boomaga GUI opens as expected when executed `boomaga` in command line as well as printed from pdf viewer like `okular`, but not when tried to print via browsers like firefox! In cups backend, jut getting `[ERROR]: can't boomaga gui` message.

Any clue appreciated!

**Comment by zenny** [comment]
Added some pointers:

```
$ sudo tail -f /var/log/cups/error_log | grep -i boomaga
E [26/Jan/2021:09:55:40 +0100] [Job 432] [Boomaga GUI] ERROR: Can\'t start boomaga gui.
```

**Comment by zenny** [comment]
This issue was solved after running the `sudo scripts/buildLocal.sh`. 

Cheers!

**Comment by Lehmeiers** [comment]
I know that this problem is already 4 years old, but now that it has hit me, I would like to know what sudo scripts/buildLocal.sh. is all about. 

Now I'm running Arch / EndeavourOS and when I try it I get the error message “sudo: scripts/buildLocal.sh: command not found” 

So if it helps, it would be great if someone could tell me where this script was from and how to proceed with it.

Many thanks in advance.

Yours sincerely, R.Lehmeier

Translated with DeepL.com (free version)
